version: '3.8'
services:
  vite-app:
    build: .
    ports:
      - "5173:5173"  # 5173ポートに変更
    volumes:
      - .:/app
      # - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true